name: 'AptyInc'
description: 'Provide a description here'
author: 'aptyInc'
inputs:
  SECRETS:
    description: "{{ toJson(secrets) }}"
    required: true
  BRANCH_NAME:
    description: branch name
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
outputs:
   FEATURE_FLAG_API_KEY:
    description: FEATURE_FLAG_API_KEY
   SEGMENT_IO_KEY:
    description: SEGMENT_IO_KEY
