name: 'AptyInc'
description: 'Extract Apty Keys'
author: 'Apty Inc'
inputs:
  SECRETS:
    description: 'JSON object of secrets'
    required: true
  BRANCH_NAME:
    description: 'Branch name'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
