name: 'AptyInc'
description: 'Extract Apty Keys'
author: 'Apty Inc'
inputs:
  SECRETS:
    description: 'JSON object of secrets'
    required: true
  BRANCH_NAME:
    description: 'Branch name'
    required: true
runs:
  using: "composite"
  steps:
    - run: ./dist/main_linux
      shell: bash
      env:
        SECRETS: ${{ inputs.SECRETS }}
        BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
