name: "build-dist"
on: # rebuild any branch changes
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.20'
      - run: go build -v -o dist/main
      - uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main
  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-windows-latest
      - name: Get Current Version
        id: get_version
        run: |
          # Get the latest tag (assuming tags are in the format vX.X)
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"

          # Parse version number and increment minor version
          version=${latest_tag#v} # Remove 'v' prefix
          major=${version%%.*}    # Extract major version
          minor=${version#*.}     # Extract minor version
          minor=${minor%%.*}      # Ensure it's a clean number
          next_minor=$((minor + 1)) # Increment minor version
          next_version="v${major}.${next_minor}"
          echo "Next version: $next_version"

          # Export as environment variable for next steps
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: Create and Push New Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List Downloaded Artifacts
        run: ls -R ./artifacts
