name: "build-dist"
on: # rebuild any branch changes
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.20'
      - run: go build -v -o dist/main
      - uses: actions/upload-artifact@v4
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main
  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v4
        with:
          name: main-windows-latest
      - name: Bump and Tag Version
        id: tag_version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
